// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package main

type NewSixsixsix struct {
	Text string `json:"text"`
}

type Sixsixsix struct {
	ID   string `json:"id"`
	Text string `json:"text"`
}
